name: Simple-test-pipline


on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JRE 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'openJDK' 
          java-package: 'JRE'
          cache: maven
      - name: Export the new jar version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          new_version=$(echo ${version} |  awk -F'.' '{print $1"."$2"."$3+1}' |  sed s/[.]$//)

      - name: update jar version to next patch
        run: mvn versions:set -DnewVersion=$new_version

      - name: Build the project
        run: mvn -B package --file pom.xml

      - name: Build the project image using DOCKERFILE
        run: docker build -t maven-hello-world:$new_version . --build-arg version=$new_version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: DOCKER_USERNAME/maven-hello-world:$new_version

      - name: Pull the docker image
        run: docker pull DOCKER_USERNAME/maven-hello-world:$new_version